# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/zhengzihang/my-src/j2me-vm

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/zhengzihang/my-src/j2me-vm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zhengzihang/my-src/j2me-vm/CMakeFiles /Users/zhengzihang/my-src/j2me-vm//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zhengzihang/my-src/j2me-vm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /Users/zhengzihang/my-src/j2me-vm/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named j2me-vm

# Build rule for target.
j2me-vm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 j2me-vm
.PHONY : j2me-vm

# fast build rule for target.
j2me-vm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/build
.PHONY : j2me-vm/fast

src/core/AudioManager.o: src/core/AudioManager.cpp.o
.PHONY : src/core/AudioManager.o

# target to build an object file
src/core/AudioManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/AudioManager.cpp.o
.PHONY : src/core/AudioManager.cpp.o

src/core/AudioManager.i: src/core/AudioManager.cpp.i
.PHONY : src/core/AudioManager.i

# target to preprocess a source file
src/core/AudioManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/AudioManager.cpp.i
.PHONY : src/core/AudioManager.cpp.i

src/core/AudioManager.s: src/core/AudioManager.cpp.s
.PHONY : src/core/AudioManager.s

# target to generate assembly for a file
src/core/AudioManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/AudioManager.cpp.s
.PHONY : src/core/AudioManager.cpp.s

src/core/ClassParser.o: src/core/ClassParser.cpp.o
.PHONY : src/core/ClassParser.o

# target to build an object file
src/core/ClassParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/ClassParser.cpp.o
.PHONY : src/core/ClassParser.cpp.o

src/core/ClassParser.i: src/core/ClassParser.cpp.i
.PHONY : src/core/ClassParser.i

# target to preprocess a source file
src/core/ClassParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/ClassParser.cpp.i
.PHONY : src/core/ClassParser.cpp.i

src/core/ClassParser.s: src/core/ClassParser.cpp.s
.PHONY : src/core/ClassParser.s

# target to generate assembly for a file
src/core/ClassParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/ClassParser.cpp.s
.PHONY : src/core/ClassParser.cpp.s

src/core/Diagnostics.o: src/core/Diagnostics.cpp.o
.PHONY : src/core/Diagnostics.o

# target to build an object file
src/core/Diagnostics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/Diagnostics.cpp.o
.PHONY : src/core/Diagnostics.cpp.o

src/core/Diagnostics.i: src/core/Diagnostics.cpp.i
.PHONY : src/core/Diagnostics.i

# target to preprocess a source file
src/core/Diagnostics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/Diagnostics.cpp.i
.PHONY : src/core/Diagnostics.cpp.i

src/core/Diagnostics.s: src/core/Diagnostics.cpp.s
.PHONY : src/core/Diagnostics.s

# target to generate assembly for a file
src/core/Diagnostics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/Diagnostics.cpp.s
.PHONY : src/core/Diagnostics.cpp.s

src/core/EventLoop.o: src/core/EventLoop.cpp.o
.PHONY : src/core/EventLoop.o

# target to build an object file
src/core/EventLoop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/EventLoop.cpp.o
.PHONY : src/core/EventLoop.cpp.o

src/core/EventLoop.i: src/core/EventLoop.cpp.i
.PHONY : src/core/EventLoop.i

# target to preprocess a source file
src/core/EventLoop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/EventLoop.cpp.i
.PHONY : src/core/EventLoop.cpp.i

src/core/EventLoop.s: src/core/EventLoop.cpp.s
.PHONY : src/core/EventLoop.s

# target to generate assembly for a file
src/core/EventLoop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/EventLoop.cpp.s
.PHONY : src/core/EventLoop.cpp.s

src/core/HeapManager.o: src/core/HeapManager.cpp.o
.PHONY : src/core/HeapManager.o

# target to build an object file
src/core/HeapManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/HeapManager.cpp.o
.PHONY : src/core/HeapManager.cpp.o

src/core/HeapManager.i: src/core/HeapManager.cpp.i
.PHONY : src/core/HeapManager.i

# target to preprocess a source file
src/core/HeapManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/HeapManager.cpp.i
.PHONY : src/core/HeapManager.cpp.i

src/core/HeapManager.s: src/core/HeapManager.cpp.s
.PHONY : src/core/HeapManager.s

# target to generate assembly for a file
src/core/HeapManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/HeapManager.cpp.s
.PHONY : src/core/HeapManager.cpp.s

src/core/Interpreter.o: src/core/Interpreter.cpp.o
.PHONY : src/core/Interpreter.o

# target to build an object file
src/core/Interpreter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/Interpreter.cpp.o
.PHONY : src/core/Interpreter.cpp.o

src/core/Interpreter.i: src/core/Interpreter.cpp.i
.PHONY : src/core/Interpreter.i

# target to preprocess a source file
src/core/Interpreter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/Interpreter.cpp.i
.PHONY : src/core/Interpreter.cpp.i

src/core/Interpreter.s: src/core/Interpreter.cpp.s
.PHONY : src/core/Interpreter.s

# target to generate assembly for a file
src/core/Interpreter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/Interpreter.cpp.s
.PHONY : src/core/Interpreter.cpp.s

src/core/Interpreter_ClassLoader.o: src/core/Interpreter_ClassLoader.cpp.o
.PHONY : src/core/Interpreter_ClassLoader.o

# target to build an object file
src/core/Interpreter_ClassLoader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/Interpreter_ClassLoader.cpp.o
.PHONY : src/core/Interpreter_ClassLoader.cpp.o

src/core/Interpreter_ClassLoader.i: src/core/Interpreter_ClassLoader.cpp.i
.PHONY : src/core/Interpreter_ClassLoader.i

# target to preprocess a source file
src/core/Interpreter_ClassLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/Interpreter_ClassLoader.cpp.i
.PHONY : src/core/Interpreter_ClassLoader.cpp.i

src/core/Interpreter_ClassLoader.s: src/core/Interpreter_ClassLoader.cpp.s
.PHONY : src/core/Interpreter_ClassLoader.s

# target to generate assembly for a file
src/core/Interpreter_ClassLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/Interpreter_ClassLoader.cpp.s
.PHONY : src/core/Interpreter_ClassLoader.cpp.s

src/core/J2MEVM.o: src/core/J2MEVM.cpp.o
.PHONY : src/core/J2MEVM.o

# target to build an object file
src/core/J2MEVM.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/J2MEVM.cpp.o
.PHONY : src/core/J2MEVM.cpp.o

src/core/J2MEVM.i: src/core/J2MEVM.cpp.i
.PHONY : src/core/J2MEVM.i

# target to preprocess a source file
src/core/J2MEVM.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/J2MEVM.cpp.i
.PHONY : src/core/J2MEVM.cpp.i

src/core/J2MEVM.s: src/core/J2MEVM.cpp.s
.PHONY : src/core/J2MEVM.s

# target to generate assembly for a file
src/core/J2MEVM.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/J2MEVM.cpp.s
.PHONY : src/core/J2MEVM.cpp.s

src/core/Logger.o: src/core/Logger.cpp.o
.PHONY : src/core/Logger.o

# target to build an object file
src/core/Logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/Logger.cpp.o
.PHONY : src/core/Logger.cpp.o

src/core/Logger.i: src/core/Logger.cpp.i
.PHONY : src/core/Logger.i

# target to preprocess a source file
src/core/Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/Logger.cpp.i
.PHONY : src/core/Logger.cpp.i

src/core/Logger.s: src/core/Logger.cpp.s
.PHONY : src/core/Logger.s

# target to generate assembly for a file
src/core/Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/Logger.cpp.s
.PHONY : src/core/Logger.cpp.s

src/core/NativeRegistry.o: src/core/NativeRegistry.cpp.o
.PHONY : src/core/NativeRegistry.o

# target to build an object file
src/core/NativeRegistry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/NativeRegistry.cpp.o
.PHONY : src/core/NativeRegistry.cpp.o

src/core/NativeRegistry.i: src/core/NativeRegistry.cpp.i
.PHONY : src/core/NativeRegistry.i

# target to preprocess a source file
src/core/NativeRegistry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/NativeRegistry.cpp.i
.PHONY : src/core/NativeRegistry.cpp.i

src/core/NativeRegistry.s: src/core/NativeRegistry.cpp.s
.PHONY : src/core/NativeRegistry.s

# target to generate assembly for a file
src/core/NativeRegistry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/NativeRegistry.cpp.s
.PHONY : src/core/NativeRegistry.cpp.s

src/core/RuntimeTypes.o: src/core/RuntimeTypes.cpp.o
.PHONY : src/core/RuntimeTypes.o

# target to build an object file
src/core/RuntimeTypes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/RuntimeTypes.cpp.o
.PHONY : src/core/RuntimeTypes.cpp.o

src/core/RuntimeTypes.i: src/core/RuntimeTypes.cpp.i
.PHONY : src/core/RuntimeTypes.i

# target to preprocess a source file
src/core/RuntimeTypes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/RuntimeTypes.cpp.i
.PHONY : src/core/RuntimeTypes.cpp.i

src/core/RuntimeTypes.s: src/core/RuntimeTypes.cpp.s
.PHONY : src/core/RuntimeTypes.s

# target to generate assembly for a file
src/core/RuntimeTypes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/RuntimeTypes.cpp.s
.PHONY : src/core/RuntimeTypes.cpp.s

src/core/StackFrame.o: src/core/StackFrame.cpp.o
.PHONY : src/core/StackFrame.o

# target to build an object file
src/core/StackFrame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/StackFrame.cpp.o
.PHONY : src/core/StackFrame.cpp.o

src/core/StackFrame.i: src/core/StackFrame.cpp.i
.PHONY : src/core/StackFrame.i

# target to preprocess a source file
src/core/StackFrame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/StackFrame.cpp.i
.PHONY : src/core/StackFrame.cpp.i

src/core/StackFrame.s: src/core/StackFrame.cpp.s
.PHONY : src/core/StackFrame.s

# target to generate assembly for a file
src/core/StackFrame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/StackFrame.cpp.s
.PHONY : src/core/StackFrame.cpp.s

src/core/instructions/Instructions_Comparisons.o: src/core/instructions/Instructions_Comparisons.cpp.o
.PHONY : src/core/instructions/Instructions_Comparisons.o

# target to build an object file
src/core/instructions/Instructions_Comparisons.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/instructions/Instructions_Comparisons.cpp.o
.PHONY : src/core/instructions/Instructions_Comparisons.cpp.o

src/core/instructions/Instructions_Comparisons.i: src/core/instructions/Instructions_Comparisons.cpp.i
.PHONY : src/core/instructions/Instructions_Comparisons.i

# target to preprocess a source file
src/core/instructions/Instructions_Comparisons.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/instructions/Instructions_Comparisons.cpp.i
.PHONY : src/core/instructions/Instructions_Comparisons.cpp.i

src/core/instructions/Instructions_Comparisons.s: src/core/instructions/Instructions_Comparisons.cpp.s
.PHONY : src/core/instructions/Instructions_Comparisons.s

# target to generate assembly for a file
src/core/instructions/Instructions_Comparisons.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/instructions/Instructions_Comparisons.cpp.s
.PHONY : src/core/instructions/Instructions_Comparisons.cpp.s

src/core/instructions/Instructions_Constants.o: src/core/instructions/Instructions_Constants.cpp.o
.PHONY : src/core/instructions/Instructions_Constants.o

# target to build an object file
src/core/instructions/Instructions_Constants.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/instructions/Instructions_Constants.cpp.o
.PHONY : src/core/instructions/Instructions_Constants.cpp.o

src/core/instructions/Instructions_Constants.i: src/core/instructions/Instructions_Constants.cpp.i
.PHONY : src/core/instructions/Instructions_Constants.i

# target to preprocess a source file
src/core/instructions/Instructions_Constants.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/instructions/Instructions_Constants.cpp.i
.PHONY : src/core/instructions/Instructions_Constants.cpp.i

src/core/instructions/Instructions_Constants.s: src/core/instructions/Instructions_Constants.cpp.s
.PHONY : src/core/instructions/Instructions_Constants.s

# target to generate assembly for a file
src/core/instructions/Instructions_Constants.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/instructions/Instructions_Constants.cpp.s
.PHONY : src/core/instructions/Instructions_Constants.cpp.s

src/core/instructions/Instructions_Control.o: src/core/instructions/Instructions_Control.cpp.o
.PHONY : src/core/instructions/Instructions_Control.o

# target to build an object file
src/core/instructions/Instructions_Control.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/instructions/Instructions_Control.cpp.o
.PHONY : src/core/instructions/Instructions_Control.cpp.o

src/core/instructions/Instructions_Control.i: src/core/instructions/Instructions_Control.cpp.i
.PHONY : src/core/instructions/Instructions_Control.i

# target to preprocess a source file
src/core/instructions/Instructions_Control.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/instructions/Instructions_Control.cpp.i
.PHONY : src/core/instructions/Instructions_Control.cpp.i

src/core/instructions/Instructions_Control.s: src/core/instructions/Instructions_Control.cpp.s
.PHONY : src/core/instructions/Instructions_Control.s

# target to generate assembly for a file
src/core/instructions/Instructions_Control.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/instructions/Instructions_Control.cpp.s
.PHONY : src/core/instructions/Instructions_Control.cpp.s

src/core/instructions/Instructions_Conversions.o: src/core/instructions/Instructions_Conversions.cpp.o
.PHONY : src/core/instructions/Instructions_Conversions.o

# target to build an object file
src/core/instructions/Instructions_Conversions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/instructions/Instructions_Conversions.cpp.o
.PHONY : src/core/instructions/Instructions_Conversions.cpp.o

src/core/instructions/Instructions_Conversions.i: src/core/instructions/Instructions_Conversions.cpp.i
.PHONY : src/core/instructions/Instructions_Conversions.i

# target to preprocess a source file
src/core/instructions/Instructions_Conversions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/instructions/Instructions_Conversions.cpp.i
.PHONY : src/core/instructions/Instructions_Conversions.cpp.i

src/core/instructions/Instructions_Conversions.s: src/core/instructions/Instructions_Conversions.cpp.s
.PHONY : src/core/instructions/Instructions_Conversions.s

# target to generate assembly for a file
src/core/instructions/Instructions_Conversions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/instructions/Instructions_Conversions.cpp.s
.PHONY : src/core/instructions/Instructions_Conversions.cpp.s

src/core/instructions/Instructions_Extended.o: src/core/instructions/Instructions_Extended.cpp.o
.PHONY : src/core/instructions/Instructions_Extended.o

# target to build an object file
src/core/instructions/Instructions_Extended.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/instructions/Instructions_Extended.cpp.o
.PHONY : src/core/instructions/Instructions_Extended.cpp.o

src/core/instructions/Instructions_Extended.i: src/core/instructions/Instructions_Extended.cpp.i
.PHONY : src/core/instructions/Instructions_Extended.i

# target to preprocess a source file
src/core/instructions/Instructions_Extended.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/instructions/Instructions_Extended.cpp.i
.PHONY : src/core/instructions/Instructions_Extended.cpp.i

src/core/instructions/Instructions_Extended.s: src/core/instructions/Instructions_Extended.cpp.s
.PHONY : src/core/instructions/Instructions_Extended.s

# target to generate assembly for a file
src/core/instructions/Instructions_Extended.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/instructions/Instructions_Extended.cpp.s
.PHONY : src/core/instructions/Instructions_Extended.cpp.s

src/core/instructions/Instructions_Loads.o: src/core/instructions/Instructions_Loads.cpp.o
.PHONY : src/core/instructions/Instructions_Loads.o

# target to build an object file
src/core/instructions/Instructions_Loads.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/instructions/Instructions_Loads.cpp.o
.PHONY : src/core/instructions/Instructions_Loads.cpp.o

src/core/instructions/Instructions_Loads.i: src/core/instructions/Instructions_Loads.cpp.i
.PHONY : src/core/instructions/Instructions_Loads.i

# target to preprocess a source file
src/core/instructions/Instructions_Loads.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/instructions/Instructions_Loads.cpp.i
.PHONY : src/core/instructions/Instructions_Loads.cpp.i

src/core/instructions/Instructions_Loads.s: src/core/instructions/Instructions_Loads.cpp.s
.PHONY : src/core/instructions/Instructions_Loads.s

# target to generate assembly for a file
src/core/instructions/Instructions_Loads.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/instructions/Instructions_Loads.cpp.s
.PHONY : src/core/instructions/Instructions_Loads.cpp.s

src/core/instructions/Instructions_Math.o: src/core/instructions/Instructions_Math.cpp.o
.PHONY : src/core/instructions/Instructions_Math.o

# target to build an object file
src/core/instructions/Instructions_Math.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/instructions/Instructions_Math.cpp.o
.PHONY : src/core/instructions/Instructions_Math.cpp.o

src/core/instructions/Instructions_Math.i: src/core/instructions/Instructions_Math.cpp.i
.PHONY : src/core/instructions/Instructions_Math.i

# target to preprocess a source file
src/core/instructions/Instructions_Math.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/instructions/Instructions_Math.cpp.i
.PHONY : src/core/instructions/Instructions_Math.cpp.i

src/core/instructions/Instructions_Math.s: src/core/instructions/Instructions_Math.cpp.s
.PHONY : src/core/instructions/Instructions_Math.s

# target to generate assembly for a file
src/core/instructions/Instructions_Math.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/instructions/Instructions_Math.cpp.s
.PHONY : src/core/instructions/Instructions_Math.cpp.s

src/core/instructions/Instructions_References.o: src/core/instructions/Instructions_References.cpp.o
.PHONY : src/core/instructions/Instructions_References.o

# target to build an object file
src/core/instructions/Instructions_References.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/instructions/Instructions_References.cpp.o
.PHONY : src/core/instructions/Instructions_References.cpp.o

src/core/instructions/Instructions_References.i: src/core/instructions/Instructions_References.cpp.i
.PHONY : src/core/instructions/Instructions_References.i

# target to preprocess a source file
src/core/instructions/Instructions_References.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/instructions/Instructions_References.cpp.i
.PHONY : src/core/instructions/Instructions_References.cpp.i

src/core/instructions/Instructions_References.s: src/core/instructions/Instructions_References.cpp.s
.PHONY : src/core/instructions/Instructions_References.s

# target to generate assembly for a file
src/core/instructions/Instructions_References.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/instructions/Instructions_References.cpp.s
.PHONY : src/core/instructions/Instructions_References.cpp.s

src/core/instructions/Instructions_Stack.o: src/core/instructions/Instructions_Stack.cpp.o
.PHONY : src/core/instructions/Instructions_Stack.o

# target to build an object file
src/core/instructions/Instructions_Stack.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/instructions/Instructions_Stack.cpp.o
.PHONY : src/core/instructions/Instructions_Stack.cpp.o

src/core/instructions/Instructions_Stack.i: src/core/instructions/Instructions_Stack.cpp.i
.PHONY : src/core/instructions/Instructions_Stack.i

# target to preprocess a source file
src/core/instructions/Instructions_Stack.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/instructions/Instructions_Stack.cpp.i
.PHONY : src/core/instructions/Instructions_Stack.cpp.i

src/core/instructions/Instructions_Stack.s: src/core/instructions/Instructions_Stack.cpp.s
.PHONY : src/core/instructions/Instructions_Stack.s

# target to generate assembly for a file
src/core/instructions/Instructions_Stack.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/instructions/Instructions_Stack.cpp.s
.PHONY : src/core/instructions/Instructions_Stack.cpp.s

src/core/instructions/Instructions_Stores.o: src/core/instructions/Instructions_Stores.cpp.o
.PHONY : src/core/instructions/Instructions_Stores.o

# target to build an object file
src/core/instructions/Instructions_Stores.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/instructions/Instructions_Stores.cpp.o
.PHONY : src/core/instructions/Instructions_Stores.cpp.o

src/core/instructions/Instructions_Stores.i: src/core/instructions/Instructions_Stores.cpp.i
.PHONY : src/core/instructions/Instructions_Stores.i

# target to preprocess a source file
src/core/instructions/Instructions_Stores.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/instructions/Instructions_Stores.cpp.i
.PHONY : src/core/instructions/Instructions_Stores.cpp.i

src/core/instructions/Instructions_Stores.s: src/core/instructions/Instructions_Stores.cpp.s
.PHONY : src/core/instructions/Instructions_Stores.s

# target to generate assembly for a file
src/core/instructions/Instructions_Stores.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/core/instructions/Instructions_Stores.cpp.s
.PHONY : src/core/instructions/Instructions_Stores.cpp.s

src/loader/JarLoader.o: src/loader/JarLoader.cpp.o
.PHONY : src/loader/JarLoader.o

# target to build an object file
src/loader/JarLoader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/loader/JarLoader.cpp.o
.PHONY : src/loader/JarLoader.cpp.o

src/loader/JarLoader.i: src/loader/JarLoader.cpp.i
.PHONY : src/loader/JarLoader.i

# target to preprocess a source file
src/loader/JarLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/loader/JarLoader.cpp.i
.PHONY : src/loader/JarLoader.cpp.i

src/loader/JarLoader.s: src/loader/JarLoader.cpp.s
.PHONY : src/loader/JarLoader.s

# target to generate assembly for a file
src/loader/JarLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/loader/JarLoader.cpp.s
.PHONY : src/loader/JarLoader.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/native/ImageCommon.o: src/native/ImageCommon.cpp.o
.PHONY : src/native/ImageCommon.o

# target to build an object file
src/native/ImageCommon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/ImageCommon.cpp.o
.PHONY : src/native/ImageCommon.cpp.o

src/native/ImageCommon.i: src/native/ImageCommon.cpp.i
.PHONY : src/native/ImageCommon.i

# target to preprocess a source file
src/native/ImageCommon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/ImageCommon.cpp.i
.PHONY : src/native/ImageCommon.cpp.i

src/native/ImageCommon.s: src/native/ImageCommon.cpp.s
.PHONY : src/native/ImageCommon.s

# target to generate assembly for a file
src/native/ImageCommon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/ImageCommon.cpp.s
.PHONY : src/native/ImageCommon.cpp.s

src/native/NativeInputStream.o: src/native/NativeInputStream.cpp.o
.PHONY : src/native/NativeInputStream.o

# target to build an object file
src/native/NativeInputStream.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/NativeInputStream.cpp.o
.PHONY : src/native/NativeInputStream.cpp.o

src/native/NativeInputStream.i: src/native/NativeInputStream.cpp.i
.PHONY : src/native/NativeInputStream.i

# target to preprocess a source file
src/native/NativeInputStream.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/NativeInputStream.cpp.i
.PHONY : src/native/NativeInputStream.cpp.i

src/native/NativeInputStream.s: src/native/NativeInputStream.cpp.s
.PHONY : src/native/NativeInputStream.s

# target to generate assembly for a file
src/native/NativeInputStream.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/NativeInputStream.cpp.s
.PHONY : src/native/NativeInputStream.cpp.s

src/native/j2me_media_AudioPlayer.o: src/native/j2me_media_AudioPlayer.cpp.o
.PHONY : src/native/j2me_media_AudioPlayer.o

# target to build an object file
src/native/j2me_media_AudioPlayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/j2me_media_AudioPlayer.cpp.o
.PHONY : src/native/j2me_media_AudioPlayer.cpp.o

src/native/j2me_media_AudioPlayer.i: src/native/j2me_media_AudioPlayer.cpp.i
.PHONY : src/native/j2me_media_AudioPlayer.i

# target to preprocess a source file
src/native/j2me_media_AudioPlayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/j2me_media_AudioPlayer.cpp.i
.PHONY : src/native/j2me_media_AudioPlayer.cpp.i

src/native/j2me_media_AudioPlayer.s: src/native/j2me_media_AudioPlayer.cpp.s
.PHONY : src/native/j2me_media_AudioPlayer.s

# target to generate assembly for a file
src/native/j2me_media_AudioPlayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/j2me_media_AudioPlayer.cpp.s
.PHONY : src/native/j2me_media_AudioPlayer.cpp.s

src/native/java_io_InputStream.o: src/native/java_io_InputStream.cpp.o
.PHONY : src/native/java_io_InputStream.o

# target to build an object file
src/native/java_io_InputStream.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_io_InputStream.cpp.o
.PHONY : src/native/java_io_InputStream.cpp.o

src/native/java_io_InputStream.i: src/native/java_io_InputStream.cpp.i
.PHONY : src/native/java_io_InputStream.i

# target to preprocess a source file
src/native/java_io_InputStream.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_io_InputStream.cpp.i
.PHONY : src/native/java_io_InputStream.cpp.i

src/native/java_io_InputStream.s: src/native/java_io_InputStream.cpp.s
.PHONY : src/native/java_io_InputStream.s

# target to generate assembly for a file
src/native/java_io_InputStream.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_io_InputStream.cpp.s
.PHONY : src/native/java_io_InputStream.cpp.s

src/native/java_io_PrintStream.o: src/native/java_io_PrintStream.cpp.o
.PHONY : src/native/java_io_PrintStream.o

# target to build an object file
src/native/java_io_PrintStream.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_io_PrintStream.cpp.o
.PHONY : src/native/java_io_PrintStream.cpp.o

src/native/java_io_PrintStream.i: src/native/java_io_PrintStream.cpp.i
.PHONY : src/native/java_io_PrintStream.i

# target to preprocess a source file
src/native/java_io_PrintStream.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_io_PrintStream.cpp.i
.PHONY : src/native/java_io_PrintStream.cpp.i

src/native/java_io_PrintStream.s: src/native/java_io_PrintStream.cpp.s
.PHONY : src/native/java_io_PrintStream.s

# target to generate assembly for a file
src/native/java_io_PrintStream.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_io_PrintStream.cpp.s
.PHONY : src/native/java_io_PrintStream.cpp.s

src/native/java_lang_Class.o: src/native/java_lang_Class.cpp.o
.PHONY : src/native/java_lang_Class.o

# target to build an object file
src/native/java_lang_Class.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_lang_Class.cpp.o
.PHONY : src/native/java_lang_Class.cpp.o

src/native/java_lang_Class.i: src/native/java_lang_Class.cpp.i
.PHONY : src/native/java_lang_Class.i

# target to preprocess a source file
src/native/java_lang_Class.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_lang_Class.cpp.i
.PHONY : src/native/java_lang_Class.cpp.i

src/native/java_lang_Class.s: src/native/java_lang_Class.cpp.s
.PHONY : src/native/java_lang_Class.s

# target to generate assembly for a file
src/native/java_lang_Class.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_lang_Class.cpp.s
.PHONY : src/native/java_lang_Class.cpp.s

src/native/java_lang_Double.o: src/native/java_lang_Double.cpp.o
.PHONY : src/native/java_lang_Double.o

# target to build an object file
src/native/java_lang_Double.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_lang_Double.cpp.o
.PHONY : src/native/java_lang_Double.cpp.o

src/native/java_lang_Double.i: src/native/java_lang_Double.cpp.i
.PHONY : src/native/java_lang_Double.i

# target to preprocess a source file
src/native/java_lang_Double.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_lang_Double.cpp.i
.PHONY : src/native/java_lang_Double.cpp.i

src/native/java_lang_Double.s: src/native/java_lang_Double.cpp.s
.PHONY : src/native/java_lang_Double.s

# target to generate assembly for a file
src/native/java_lang_Double.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_lang_Double.cpp.s
.PHONY : src/native/java_lang_Double.cpp.s

src/native/java_lang_Float.o: src/native/java_lang_Float.cpp.o
.PHONY : src/native/java_lang_Float.o

# target to build an object file
src/native/java_lang_Float.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_lang_Float.cpp.o
.PHONY : src/native/java_lang_Float.cpp.o

src/native/java_lang_Float.i: src/native/java_lang_Float.cpp.i
.PHONY : src/native/java_lang_Float.i

# target to preprocess a source file
src/native/java_lang_Float.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_lang_Float.cpp.i
.PHONY : src/native/java_lang_Float.cpp.i

src/native/java_lang_Float.s: src/native/java_lang_Float.cpp.s
.PHONY : src/native/java_lang_Float.s

# target to generate assembly for a file
src/native/java_lang_Float.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_lang_Float.cpp.s
.PHONY : src/native/java_lang_Float.cpp.s

src/native/java_lang_Math.o: src/native/java_lang_Math.cpp.o
.PHONY : src/native/java_lang_Math.o

# target to build an object file
src/native/java_lang_Math.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_lang_Math.cpp.o
.PHONY : src/native/java_lang_Math.cpp.o

src/native/java_lang_Math.i: src/native/java_lang_Math.cpp.i
.PHONY : src/native/java_lang_Math.i

# target to preprocess a source file
src/native/java_lang_Math.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_lang_Math.cpp.i
.PHONY : src/native/java_lang_Math.cpp.i

src/native/java_lang_Math.s: src/native/java_lang_Math.cpp.s
.PHONY : src/native/java_lang_Math.s

# target to generate assembly for a file
src/native/java_lang_Math.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_lang_Math.cpp.s
.PHONY : src/native/java_lang_Math.cpp.s

src/native/java_lang_Object.o: src/native/java_lang_Object.cpp.o
.PHONY : src/native/java_lang_Object.o

# target to build an object file
src/native/java_lang_Object.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_lang_Object.cpp.o
.PHONY : src/native/java_lang_Object.cpp.o

src/native/java_lang_Object.i: src/native/java_lang_Object.cpp.i
.PHONY : src/native/java_lang_Object.i

# target to preprocess a source file
src/native/java_lang_Object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_lang_Object.cpp.i
.PHONY : src/native/java_lang_Object.cpp.i

src/native/java_lang_Object.s: src/native/java_lang_Object.cpp.s
.PHONY : src/native/java_lang_Object.s

# target to generate assembly for a file
src/native/java_lang_Object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_lang_Object.cpp.s
.PHONY : src/native/java_lang_Object.cpp.s

src/native/java_lang_String.o: src/native/java_lang_String.cpp.o
.PHONY : src/native/java_lang_String.o

# target to build an object file
src/native/java_lang_String.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_lang_String.cpp.o
.PHONY : src/native/java_lang_String.cpp.o

src/native/java_lang_String.i: src/native/java_lang_String.cpp.i
.PHONY : src/native/java_lang_String.i

# target to preprocess a source file
src/native/java_lang_String.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_lang_String.cpp.i
.PHONY : src/native/java_lang_String.cpp.i

src/native/java_lang_String.s: src/native/java_lang_String.cpp.s
.PHONY : src/native/java_lang_String.s

# target to generate assembly for a file
src/native/java_lang_String.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_lang_String.cpp.s
.PHONY : src/native/java_lang_String.cpp.s

src/native/java_lang_StringBuffer.o: src/native/java_lang_StringBuffer.cpp.o
.PHONY : src/native/java_lang_StringBuffer.o

# target to build an object file
src/native/java_lang_StringBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_lang_StringBuffer.cpp.o
.PHONY : src/native/java_lang_StringBuffer.cpp.o

src/native/java_lang_StringBuffer.i: src/native/java_lang_StringBuffer.cpp.i
.PHONY : src/native/java_lang_StringBuffer.i

# target to preprocess a source file
src/native/java_lang_StringBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_lang_StringBuffer.cpp.i
.PHONY : src/native/java_lang_StringBuffer.cpp.i

src/native/java_lang_StringBuffer.s: src/native/java_lang_StringBuffer.cpp.s
.PHONY : src/native/java_lang_StringBuffer.s

# target to generate assembly for a file
src/native/java_lang_StringBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_lang_StringBuffer.cpp.s
.PHONY : src/native/java_lang_StringBuffer.cpp.s

src/native/java_lang_System.o: src/native/java_lang_System.cpp.o
.PHONY : src/native/java_lang_System.o

# target to build an object file
src/native/java_lang_System.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_lang_System.cpp.o
.PHONY : src/native/java_lang_System.cpp.o

src/native/java_lang_System.i: src/native/java_lang_System.cpp.i
.PHONY : src/native/java_lang_System.i

# target to preprocess a source file
src/native/java_lang_System.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_lang_System.cpp.i
.PHONY : src/native/java_lang_System.cpp.i

src/native/java_lang_System.s: src/native/java_lang_System.cpp.s
.PHONY : src/native/java_lang_System.s

# target to generate assembly for a file
src/native/java_lang_System.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_lang_System.cpp.s
.PHONY : src/native/java_lang_System.cpp.s

src/native/java_lang_Thread.o: src/native/java_lang_Thread.cpp.o
.PHONY : src/native/java_lang_Thread.o

# target to build an object file
src/native/java_lang_Thread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_lang_Thread.cpp.o
.PHONY : src/native/java_lang_Thread.cpp.o

src/native/java_lang_Thread.i: src/native/java_lang_Thread.cpp.i
.PHONY : src/native/java_lang_Thread.i

# target to preprocess a source file
src/native/java_lang_Thread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_lang_Thread.cpp.i
.PHONY : src/native/java_lang_Thread.cpp.i

src/native/java_lang_Thread.s: src/native/java_lang_Thread.cpp.s
.PHONY : src/native/java_lang_Thread.s

# target to generate assembly for a file
src/native/java_lang_Thread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_lang_Thread.cpp.s
.PHONY : src/native/java_lang_Thread.cpp.s

src/native/java_util_Timer.o: src/native/java_util_Timer.cpp.o
.PHONY : src/native/java_util_Timer.o

# target to build an object file
src/native/java_util_Timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_util_Timer.cpp.o
.PHONY : src/native/java_util_Timer.cpp.o

src/native/java_util_Timer.i: src/native/java_util_Timer.cpp.i
.PHONY : src/native/java_util_Timer.i

# target to preprocess a source file
src/native/java_util_Timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_util_Timer.cpp.i
.PHONY : src/native/java_util_Timer.cpp.i

src/native/java_util_Timer.s: src/native/java_util_Timer.cpp.s
.PHONY : src/native/java_util_Timer.s

# target to generate assembly for a file
src/native/java_util_Timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/java_util_Timer.cpp.s
.PHONY : src/native/java_util_Timer.cpp.s

src/native/javax_microedition_io_Connector.o: src/native/javax_microedition_io_Connector.cpp.o
.PHONY : src/native/javax_microedition_io_Connector.o

# target to build an object file
src/native/javax_microedition_io_Connector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/javax_microedition_io_Connector.cpp.o
.PHONY : src/native/javax_microedition_io_Connector.cpp.o

src/native/javax_microedition_io_Connector.i: src/native/javax_microedition_io_Connector.cpp.i
.PHONY : src/native/javax_microedition_io_Connector.i

# target to preprocess a source file
src/native/javax_microedition_io_Connector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/javax_microedition_io_Connector.cpp.i
.PHONY : src/native/javax_microedition_io_Connector.cpp.i

src/native/javax_microedition_io_Connector.s: src/native/javax_microedition_io_Connector.cpp.s
.PHONY : src/native/javax_microedition_io_Connector.s

# target to generate assembly for a file
src/native/javax_microedition_io_Connector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/javax_microedition_io_Connector.cpp.s
.PHONY : src/native/javax_microedition_io_Connector.cpp.s

src/native/javax_microedition_lcdui_Display.o: src/native/javax_microedition_lcdui_Display.cpp.o
.PHONY : src/native/javax_microedition_lcdui_Display.o

# target to build an object file
src/native/javax_microedition_lcdui_Display.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/javax_microedition_lcdui_Display.cpp.o
.PHONY : src/native/javax_microedition_lcdui_Display.cpp.o

src/native/javax_microedition_lcdui_Display.i: src/native/javax_microedition_lcdui_Display.cpp.i
.PHONY : src/native/javax_microedition_lcdui_Display.i

# target to preprocess a source file
src/native/javax_microedition_lcdui_Display.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/javax_microedition_lcdui_Display.cpp.i
.PHONY : src/native/javax_microedition_lcdui_Display.cpp.i

src/native/javax_microedition_lcdui_Display.s: src/native/javax_microedition_lcdui_Display.cpp.s
.PHONY : src/native/javax_microedition_lcdui_Display.s

# target to generate assembly for a file
src/native/javax_microedition_lcdui_Display.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/javax_microedition_lcdui_Display.cpp.s
.PHONY : src/native/javax_microedition_lcdui_Display.cpp.s

src/native/javax_microedition_lcdui_Font.o: src/native/javax_microedition_lcdui_Font.cpp.o
.PHONY : src/native/javax_microedition_lcdui_Font.o

# target to build an object file
src/native/javax_microedition_lcdui_Font.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/javax_microedition_lcdui_Font.cpp.o
.PHONY : src/native/javax_microedition_lcdui_Font.cpp.o

src/native/javax_microedition_lcdui_Font.i: src/native/javax_microedition_lcdui_Font.cpp.i
.PHONY : src/native/javax_microedition_lcdui_Font.i

# target to preprocess a source file
src/native/javax_microedition_lcdui_Font.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/javax_microedition_lcdui_Font.cpp.i
.PHONY : src/native/javax_microedition_lcdui_Font.cpp.i

src/native/javax_microedition_lcdui_Font.s: src/native/javax_microedition_lcdui_Font.cpp.s
.PHONY : src/native/javax_microedition_lcdui_Font.s

# target to generate assembly for a file
src/native/javax_microedition_lcdui_Font.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/javax_microedition_lcdui_Font.cpp.s
.PHONY : src/native/javax_microedition_lcdui_Font.cpp.s

src/native/javax_microedition_lcdui_Graphics.o: src/native/javax_microedition_lcdui_Graphics.cpp.o
.PHONY : src/native/javax_microedition_lcdui_Graphics.o

# target to build an object file
src/native/javax_microedition_lcdui_Graphics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/javax_microedition_lcdui_Graphics.cpp.o
.PHONY : src/native/javax_microedition_lcdui_Graphics.cpp.o

src/native/javax_microedition_lcdui_Graphics.i: src/native/javax_microedition_lcdui_Graphics.cpp.i
.PHONY : src/native/javax_microedition_lcdui_Graphics.i

# target to preprocess a source file
src/native/javax_microedition_lcdui_Graphics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/javax_microedition_lcdui_Graphics.cpp.i
.PHONY : src/native/javax_microedition_lcdui_Graphics.cpp.i

src/native/javax_microedition_lcdui_Graphics.s: src/native/javax_microedition_lcdui_Graphics.cpp.s
.PHONY : src/native/javax_microedition_lcdui_Graphics.s

# target to generate assembly for a file
src/native/javax_microedition_lcdui_Graphics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/javax_microedition_lcdui_Graphics.cpp.s
.PHONY : src/native/javax_microedition_lcdui_Graphics.cpp.s

src/native/javax_microedition_lcdui_Image.o: src/native/javax_microedition_lcdui_Image.cpp.o
.PHONY : src/native/javax_microedition_lcdui_Image.o

# target to build an object file
src/native/javax_microedition_lcdui_Image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/javax_microedition_lcdui_Image.cpp.o
.PHONY : src/native/javax_microedition_lcdui_Image.cpp.o

src/native/javax_microedition_lcdui_Image.i: src/native/javax_microedition_lcdui_Image.cpp.i
.PHONY : src/native/javax_microedition_lcdui_Image.i

# target to preprocess a source file
src/native/javax_microedition_lcdui_Image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/javax_microedition_lcdui_Image.cpp.i
.PHONY : src/native/javax_microedition_lcdui_Image.cpp.i

src/native/javax_microedition_lcdui_Image.s: src/native/javax_microedition_lcdui_Image.cpp.s
.PHONY : src/native/javax_microedition_lcdui_Image.s

# target to generate assembly for a file
src/native/javax_microedition_lcdui_Image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/javax_microedition_lcdui_Image.cpp.s
.PHONY : src/native/javax_microedition_lcdui_Image.cpp.s

src/native/javax_microedition_lcdui_game_GameCanvas.o: src/native/javax_microedition_lcdui_game_GameCanvas.cpp.o
.PHONY : src/native/javax_microedition_lcdui_game_GameCanvas.o

# target to build an object file
src/native/javax_microedition_lcdui_game_GameCanvas.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/javax_microedition_lcdui_game_GameCanvas.cpp.o
.PHONY : src/native/javax_microedition_lcdui_game_GameCanvas.cpp.o

src/native/javax_microedition_lcdui_game_GameCanvas.i: src/native/javax_microedition_lcdui_game_GameCanvas.cpp.i
.PHONY : src/native/javax_microedition_lcdui_game_GameCanvas.i

# target to preprocess a source file
src/native/javax_microedition_lcdui_game_GameCanvas.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/javax_microedition_lcdui_game_GameCanvas.cpp.i
.PHONY : src/native/javax_microedition_lcdui_game_GameCanvas.cpp.i

src/native/javax_microedition_lcdui_game_GameCanvas.s: src/native/javax_microedition_lcdui_game_GameCanvas.cpp.s
.PHONY : src/native/javax_microedition_lcdui_game_GameCanvas.s

# target to generate assembly for a file
src/native/javax_microedition_lcdui_game_GameCanvas.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/javax_microedition_lcdui_game_GameCanvas.cpp.s
.PHONY : src/native/javax_microedition_lcdui_game_GameCanvas.cpp.s

src/native/javax_microedition_lcdui_game_Sprite.o: src/native/javax_microedition_lcdui_game_Sprite.cpp.o
.PHONY : src/native/javax_microedition_lcdui_game_Sprite.o

# target to build an object file
src/native/javax_microedition_lcdui_game_Sprite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/javax_microedition_lcdui_game_Sprite.cpp.o
.PHONY : src/native/javax_microedition_lcdui_game_Sprite.cpp.o

src/native/javax_microedition_lcdui_game_Sprite.i: src/native/javax_microedition_lcdui_game_Sprite.cpp.i
.PHONY : src/native/javax_microedition_lcdui_game_Sprite.i

# target to preprocess a source file
src/native/javax_microedition_lcdui_game_Sprite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/javax_microedition_lcdui_game_Sprite.cpp.i
.PHONY : src/native/javax_microedition_lcdui_game_Sprite.cpp.i

src/native/javax_microedition_lcdui_game_Sprite.s: src/native/javax_microedition_lcdui_game_Sprite.cpp.s
.PHONY : src/native/javax_microedition_lcdui_game_Sprite.s

# target to generate assembly for a file
src/native/javax_microedition_lcdui_game_Sprite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/javax_microedition_lcdui_game_Sprite.cpp.s
.PHONY : src/native/javax_microedition_lcdui_game_Sprite.cpp.s

src/native/javax_microedition_lcdui_game_TiledLayer.o: src/native/javax_microedition_lcdui_game_TiledLayer.cpp.o
.PHONY : src/native/javax_microedition_lcdui_game_TiledLayer.o

# target to build an object file
src/native/javax_microedition_lcdui_game_TiledLayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/javax_microedition_lcdui_game_TiledLayer.cpp.o
.PHONY : src/native/javax_microedition_lcdui_game_TiledLayer.cpp.o

src/native/javax_microedition_lcdui_game_TiledLayer.i: src/native/javax_microedition_lcdui_game_TiledLayer.cpp.i
.PHONY : src/native/javax_microedition_lcdui_game_TiledLayer.i

# target to preprocess a source file
src/native/javax_microedition_lcdui_game_TiledLayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/javax_microedition_lcdui_game_TiledLayer.cpp.i
.PHONY : src/native/javax_microedition_lcdui_game_TiledLayer.cpp.i

src/native/javax_microedition_lcdui_game_TiledLayer.s: src/native/javax_microedition_lcdui_game_TiledLayer.cpp.s
.PHONY : src/native/javax_microedition_lcdui_game_TiledLayer.s

# target to generate assembly for a file
src/native/javax_microedition_lcdui_game_TiledLayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/javax_microedition_lcdui_game_TiledLayer.cpp.s
.PHONY : src/native/javax_microedition_lcdui_game_TiledLayer.cpp.s

src/native/javax_microedition_media_Manager.o: src/native/javax_microedition_media_Manager.cpp.o
.PHONY : src/native/javax_microedition_media_Manager.o

# target to build an object file
src/native/javax_microedition_media_Manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/javax_microedition_media_Manager.cpp.o
.PHONY : src/native/javax_microedition_media_Manager.cpp.o

src/native/javax_microedition_media_Manager.i: src/native/javax_microedition_media_Manager.cpp.i
.PHONY : src/native/javax_microedition_media_Manager.i

# target to preprocess a source file
src/native/javax_microedition_media_Manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/javax_microedition_media_Manager.cpp.i
.PHONY : src/native/javax_microedition_media_Manager.cpp.i

src/native/javax_microedition_media_Manager.s: src/native/javax_microedition_media_Manager.cpp.s
.PHONY : src/native/javax_microedition_media_Manager.s

# target to generate assembly for a file
src/native/javax_microedition_media_Manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/javax_microedition_media_Manager.cpp.s
.PHONY : src/native/javax_microedition_media_Manager.cpp.s

src/native/javax_microedition_rms_RecordStore.o: src/native/javax_microedition_rms_RecordStore.cpp.o
.PHONY : src/native/javax_microedition_rms_RecordStore.o

# target to build an object file
src/native/javax_microedition_rms_RecordStore.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/javax_microedition_rms_RecordStore.cpp.o
.PHONY : src/native/javax_microedition_rms_RecordStore.cpp.o

src/native/javax_microedition_rms_RecordStore.i: src/native/javax_microedition_rms_RecordStore.cpp.i
.PHONY : src/native/javax_microedition_rms_RecordStore.i

# target to preprocess a source file
src/native/javax_microedition_rms_RecordStore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/javax_microedition_rms_RecordStore.cpp.i
.PHONY : src/native/javax_microedition_rms_RecordStore.cpp.i

src/native/javax_microedition_rms_RecordStore.s: src/native/javax_microedition_rms_RecordStore.cpp.s
.PHONY : src/native/javax_microedition_rms_RecordStore.s

# target to generate assembly for a file
src/native/javax_microedition_rms_RecordStore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/native/javax_microedition_rms_RecordStore.cpp.s
.PHONY : src/native/javax_microedition_rms_RecordStore.cpp.s

src/platform/GraphicsContext.o: src/platform/GraphicsContext.cpp.o
.PHONY : src/platform/GraphicsContext.o

# target to build an object file
src/platform/GraphicsContext.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/platform/GraphicsContext.cpp.o
.PHONY : src/platform/GraphicsContext.cpp.o

src/platform/GraphicsContext.i: src/platform/GraphicsContext.cpp.i
.PHONY : src/platform/GraphicsContext.i

# target to preprocess a source file
src/platform/GraphicsContext.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/platform/GraphicsContext.cpp.i
.PHONY : src/platform/GraphicsContext.cpp.i

src/platform/GraphicsContext.s: src/platform/GraphicsContext.cpp.s
.PHONY : src/platform/GraphicsContext.s

# target to generate assembly for a file
src/platform/GraphicsContext.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/platform/GraphicsContext.cpp.s
.PHONY : src/platform/GraphicsContext.cpp.s

src/util/FileUtils.o: src/util/FileUtils.cpp.o
.PHONY : src/util/FileUtils.o

# target to build an object file
src/util/FileUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/util/FileUtils.cpp.o
.PHONY : src/util/FileUtils.cpp.o

src/util/FileUtils.i: src/util/FileUtils.cpp.i
.PHONY : src/util/FileUtils.i

# target to preprocess a source file
src/util/FileUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/util/FileUtils.cpp.i
.PHONY : src/util/FileUtils.cpp.i

src/util/FileUtils.s: src/util/FileUtils.cpp.s
.PHONY : src/util/FileUtils.s

# target to generate assembly for a file
src/util/FileUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/j2me-vm.dir/build.make CMakeFiles/j2me-vm.dir/src/util/FileUtils.cpp.s
.PHONY : src/util/FileUtils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... j2me-vm"
	@echo "... src/core/AudioManager.o"
	@echo "... src/core/AudioManager.i"
	@echo "... src/core/AudioManager.s"
	@echo "... src/core/ClassParser.o"
	@echo "... src/core/ClassParser.i"
	@echo "... src/core/ClassParser.s"
	@echo "... src/core/Diagnostics.o"
	@echo "... src/core/Diagnostics.i"
	@echo "... src/core/Diagnostics.s"
	@echo "... src/core/EventLoop.o"
	@echo "... src/core/EventLoop.i"
	@echo "... src/core/EventLoop.s"
	@echo "... src/core/HeapManager.o"
	@echo "... src/core/HeapManager.i"
	@echo "... src/core/HeapManager.s"
	@echo "... src/core/Interpreter.o"
	@echo "... src/core/Interpreter.i"
	@echo "... src/core/Interpreter.s"
	@echo "... src/core/Interpreter_ClassLoader.o"
	@echo "... src/core/Interpreter_ClassLoader.i"
	@echo "... src/core/Interpreter_ClassLoader.s"
	@echo "... src/core/J2MEVM.o"
	@echo "... src/core/J2MEVM.i"
	@echo "... src/core/J2MEVM.s"
	@echo "... src/core/Logger.o"
	@echo "... src/core/Logger.i"
	@echo "... src/core/Logger.s"
	@echo "... src/core/NativeRegistry.o"
	@echo "... src/core/NativeRegistry.i"
	@echo "... src/core/NativeRegistry.s"
	@echo "... src/core/RuntimeTypes.o"
	@echo "... src/core/RuntimeTypes.i"
	@echo "... src/core/RuntimeTypes.s"
	@echo "... src/core/StackFrame.o"
	@echo "... src/core/StackFrame.i"
	@echo "... src/core/StackFrame.s"
	@echo "... src/core/instructions/Instructions_Comparisons.o"
	@echo "... src/core/instructions/Instructions_Comparisons.i"
	@echo "... src/core/instructions/Instructions_Comparisons.s"
	@echo "... src/core/instructions/Instructions_Constants.o"
	@echo "... src/core/instructions/Instructions_Constants.i"
	@echo "... src/core/instructions/Instructions_Constants.s"
	@echo "... src/core/instructions/Instructions_Control.o"
	@echo "... src/core/instructions/Instructions_Control.i"
	@echo "... src/core/instructions/Instructions_Control.s"
	@echo "... src/core/instructions/Instructions_Conversions.o"
	@echo "... src/core/instructions/Instructions_Conversions.i"
	@echo "... src/core/instructions/Instructions_Conversions.s"
	@echo "... src/core/instructions/Instructions_Extended.o"
	@echo "... src/core/instructions/Instructions_Extended.i"
	@echo "... src/core/instructions/Instructions_Extended.s"
	@echo "... src/core/instructions/Instructions_Loads.o"
	@echo "... src/core/instructions/Instructions_Loads.i"
	@echo "... src/core/instructions/Instructions_Loads.s"
	@echo "... src/core/instructions/Instructions_Math.o"
	@echo "... src/core/instructions/Instructions_Math.i"
	@echo "... src/core/instructions/Instructions_Math.s"
	@echo "... src/core/instructions/Instructions_References.o"
	@echo "... src/core/instructions/Instructions_References.i"
	@echo "... src/core/instructions/Instructions_References.s"
	@echo "... src/core/instructions/Instructions_Stack.o"
	@echo "... src/core/instructions/Instructions_Stack.i"
	@echo "... src/core/instructions/Instructions_Stack.s"
	@echo "... src/core/instructions/Instructions_Stores.o"
	@echo "... src/core/instructions/Instructions_Stores.i"
	@echo "... src/core/instructions/Instructions_Stores.s"
	@echo "... src/loader/JarLoader.o"
	@echo "... src/loader/JarLoader.i"
	@echo "... src/loader/JarLoader.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/native/ImageCommon.o"
	@echo "... src/native/ImageCommon.i"
	@echo "... src/native/ImageCommon.s"
	@echo "... src/native/NativeInputStream.o"
	@echo "... src/native/NativeInputStream.i"
	@echo "... src/native/NativeInputStream.s"
	@echo "... src/native/j2me_media_AudioPlayer.o"
	@echo "... src/native/j2me_media_AudioPlayer.i"
	@echo "... src/native/j2me_media_AudioPlayer.s"
	@echo "... src/native/java_io_InputStream.o"
	@echo "... src/native/java_io_InputStream.i"
	@echo "... src/native/java_io_InputStream.s"
	@echo "... src/native/java_io_PrintStream.o"
	@echo "... src/native/java_io_PrintStream.i"
	@echo "... src/native/java_io_PrintStream.s"
	@echo "... src/native/java_lang_Class.o"
	@echo "... src/native/java_lang_Class.i"
	@echo "... src/native/java_lang_Class.s"
	@echo "... src/native/java_lang_Double.o"
	@echo "... src/native/java_lang_Double.i"
	@echo "... src/native/java_lang_Double.s"
	@echo "... src/native/java_lang_Float.o"
	@echo "... src/native/java_lang_Float.i"
	@echo "... src/native/java_lang_Float.s"
	@echo "... src/native/java_lang_Math.o"
	@echo "... src/native/java_lang_Math.i"
	@echo "... src/native/java_lang_Math.s"
	@echo "... src/native/java_lang_Object.o"
	@echo "... src/native/java_lang_Object.i"
	@echo "... src/native/java_lang_Object.s"
	@echo "... src/native/java_lang_String.o"
	@echo "... src/native/java_lang_String.i"
	@echo "... src/native/java_lang_String.s"
	@echo "... src/native/java_lang_StringBuffer.o"
	@echo "... src/native/java_lang_StringBuffer.i"
	@echo "... src/native/java_lang_StringBuffer.s"
	@echo "... src/native/java_lang_System.o"
	@echo "... src/native/java_lang_System.i"
	@echo "... src/native/java_lang_System.s"
	@echo "... src/native/java_lang_Thread.o"
	@echo "... src/native/java_lang_Thread.i"
	@echo "... src/native/java_lang_Thread.s"
	@echo "... src/native/java_util_Timer.o"
	@echo "... src/native/java_util_Timer.i"
	@echo "... src/native/java_util_Timer.s"
	@echo "... src/native/javax_microedition_io_Connector.o"
	@echo "... src/native/javax_microedition_io_Connector.i"
	@echo "... src/native/javax_microedition_io_Connector.s"
	@echo "... src/native/javax_microedition_lcdui_Display.o"
	@echo "... src/native/javax_microedition_lcdui_Display.i"
	@echo "... src/native/javax_microedition_lcdui_Display.s"
	@echo "... src/native/javax_microedition_lcdui_Font.o"
	@echo "... src/native/javax_microedition_lcdui_Font.i"
	@echo "... src/native/javax_microedition_lcdui_Font.s"
	@echo "... src/native/javax_microedition_lcdui_Graphics.o"
	@echo "... src/native/javax_microedition_lcdui_Graphics.i"
	@echo "... src/native/javax_microedition_lcdui_Graphics.s"
	@echo "... src/native/javax_microedition_lcdui_Image.o"
	@echo "... src/native/javax_microedition_lcdui_Image.i"
	@echo "... src/native/javax_microedition_lcdui_Image.s"
	@echo "... src/native/javax_microedition_lcdui_game_GameCanvas.o"
	@echo "... src/native/javax_microedition_lcdui_game_GameCanvas.i"
	@echo "... src/native/javax_microedition_lcdui_game_GameCanvas.s"
	@echo "... src/native/javax_microedition_lcdui_game_Sprite.o"
	@echo "... src/native/javax_microedition_lcdui_game_Sprite.i"
	@echo "... src/native/javax_microedition_lcdui_game_Sprite.s"
	@echo "... src/native/javax_microedition_lcdui_game_TiledLayer.o"
	@echo "... src/native/javax_microedition_lcdui_game_TiledLayer.i"
	@echo "... src/native/javax_microedition_lcdui_game_TiledLayer.s"
	@echo "... src/native/javax_microedition_media_Manager.o"
	@echo "... src/native/javax_microedition_media_Manager.i"
	@echo "... src/native/javax_microedition_media_Manager.s"
	@echo "... src/native/javax_microedition_rms_RecordStore.o"
	@echo "... src/native/javax_microedition_rms_RecordStore.i"
	@echo "... src/native/javax_microedition_rms_RecordStore.s"
	@echo "... src/platform/GraphicsContext.o"
	@echo "... src/platform/GraphicsContext.i"
	@echo "... src/platform/GraphicsContext.s"
	@echo "... src/util/FileUtils.o"
	@echo "... src/util/FileUtils.i"
	@echo "... src/util/FileUtils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /Users/zhengzihang/my-src/j2me-vm/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

